/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Category = IDL.Record({
  'id' : IDL.Text,
  'active' : IDL.Bool,
  'order' : IDL.Nat,
  'icon' : IDL.Text,
  'name' : IDL.Text,
  'color' : IDL.Text,
});
export const Creator = IDL.Record({
  'id' : IDL.Text,
  'bio' : IDL.Text,
  'verified' : IDL.Bool,
  'name' : IDL.Text,
  'totalVideos' : IDL.Nat,
  'followers' : IDL.Nat,
  'avatar' : IDL.Text,
});
export const Status = IDL.Variant({
  'active' : IDL.Null,
  'draft' : IDL.Null,
  'archived' : IDL.Null,
});
export const Drama = IDL.Record({
  'id' : IDL.Text,
  'categoryId' : IDL.Text,
  'status' : Status,
  'title' : IDL.Text,
  'shares' : IDL.Nat,
  'thumbnail' : IDL.Text,
  'views' : IDL.Nat,
  'isPremium' : IDL.Bool,
  'coinsRequired' : IDL.Nat,
  'createdAt' : IDL.Int,
  'tags' : IDL.Vec(IDL.Text),
  'creatorId' : IDL.Text,
  'description' : IDL.Text,
  'likes' : IDL.Nat,
  'updatedAt' : IDL.Int,
  'totalParts' : IDL.Nat,
});
export const Episode = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'duration' : IDL.Nat,
  'thumbnail' : IDL.Text,
  'partNumber' : IDL.Nat,
  'order' : IDL.Nat,
  'views' : IDL.Nat,
  'isPremium' : IDL.Bool,
  'coinsRequired' : IDL.Nat,
  'createdAt' : IDL.Int,
  'videoUrl' : IDL.Text,
  'dramaId' : IDL.Text,
});
export const AppConfig = IDL.Record({
  'vipMonthlyPrice' : IDL.Float64,
  'maintenanceMode' : IDL.Bool,
  'vipYearlyPrice' : IDL.Float64,
  'coinRewardPerAd' : IDL.Nat,
  'dailyBonusCoins' : IDL.Nat,
});
export const TransactionType = IDL.Variant({
  'adReward' : IDL.Null,
  'vipPurchase' : IDL.Null,
  'episodeUnlock' : IDL.Null,
  'dailyBonus' : IDL.Null,
  'purchase' : IDL.Null,
});
export const CoinTransaction = IDL.Record({
  'id' : IDL.Text,
  'transactionType' : TransactionType,
  'userId' : IDL.Nat,
  'createdAt' : IDL.Int,
  'description' : IDL.Text,
  'amount' : IDL.Int,
});
export const AnalyticsDay = IDL.Record({
  'activeUsers' : IDL.Nat,
  'revenue' : IDL.Float64,
  'totalViews' : IDL.Nat,
  'date' : IDL.Text,
  'totalUsers' : IDL.Nat,
  'newUsers' : IDL.Nat,
  'coinsDistributed' : IDL.Nat,
});
export const TargetAudience = IDL.Variant({
  'all' : IDL.Null,
  'vip' : IDL.Null,
  'free' : IDL.Null,
});
export const Notification = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'body' : IDL.Text,
  'sentAt' : IDL.Int,
  'sentBy' : IDL.Text,
  'targetAudience' : TargetAudience,
  'imageUrl' : IDL.Text,
});
export const SubscriptionStatus = IDL.Variant({
  'active' : IDL.Null,
  'cancelled' : IDL.Null,
  'expired' : IDL.Null,
});
export const SubscriptionPlan = IDL.Variant({
  'monthly' : IDL.Null,
  'yearly' : IDL.Null,
});
export const Subscription = IDL.Record({
  'id' : IDL.Text,
  'status' : SubscriptionStatus,
  'endDate' : IDL.Int,
  'userId' : IDL.Nat,
  'plan' : SubscriptionPlan,
  'price' : IDL.Float64,
  'startDate' : IDL.Int,
});
export const User = IDL.Record({
  'id' : IDL.Nat,
  'favorites' : IDL.Vec(IDL.Text),
  'displayName' : IDL.Text,
  'isBlocked' : IDL.Bool,
  'createdAt' : IDL.Int,
  'coins' : IDL.Nat,
  'watchHistory' : IDL.Vec(IDL.Text),
  'isVIP' : IDL.Bool,
  'phone' : IDL.Text,
  'following' : IDL.Vec(IDL.Text),
  'vipExpiry' : IDL.Opt(IDL.Int),
  'dailyRewardClaimed' : IDL.Bool,
  'avatar' : IDL.Text,
});

export const idlService = IDL.Service({
  'adjustUserCoins' : IDL.Func([IDL.Nat, IDL.Int, IDL.Text], [IDL.Bool], []),
  'blockUser' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'createCategory' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Nat],
      [Category],
      [],
    ),
  'createCreator' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [Creator],
      [],
    ),
  'createDrama' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Vec(IDL.Text),
        IDL.Bool,
        IDL.Nat,
      ],
      [Drama],
      [],
    ),
  'createEpisode' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        IDL.Bool,
        IDL.Nat,
      ],
      [Episode],
      [],
    ),
  'deleteCategory' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'deleteDrama' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'deleteEpisode' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'getAppConfig' : IDL.Func([], [AppConfig], ['query']),
  'getCategories' : IDL.Func([], [IDL.Vec(Category)], []),
  'getCoinTransactions' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(CoinTransaction)],
      ['query'],
    ),
  'getCreators' : IDL.Func([], [IDL.Vec(Creator)], ['query']),
  'getDailyAnalytics' : IDL.Func([IDL.Nat], [IDL.Vec(AnalyticsDay)], ['query']),
  'getDrama' : IDL.Func([IDL.Text], [IDL.Opt(Drama)], []),
  'getDramas' : IDL.Func([], [IDL.Vec(Drama)], []),
  'getEpisodesByDrama' : IDL.Func([IDL.Text], [IDL.Vec(Episode)], []),
  'getNotifications' : IDL.Func([], [IDL.Vec(Notification)], ['query']),
  'getSubscriptions' : IDL.Func([], [IDL.Vec(Subscription)], ['query']),
  'getSummaryStats' : IDL.Func(
      [],
      [
        IDL.Record({
          'revenue' : IDL.Float64,
          'totalViews' : IDL.Nat,
          'activeToday' : IDL.Nat,
          'totalUsers' : IDL.Nat,
        }),
      ],
      ['query'],
    ),
  'getUser' : IDL.Func([IDL.Nat], [IDL.Opt(User)], ['query']),
  'getUserTransactions' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(CoinTransaction)],
      ['query'],
    ),
  'getUsers' : IDL.Func([], [IDL.Vec(User)], ['query']),
  'preupgrade' : IDL.Func([], [], ['oneway']),
  'reorderEpisode' : IDL.Func([IDL.Text, IDL.Nat], [IDL.Bool], []),
  'sendNotification' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, TargetAudience, IDL.Text],
      [Notification],
      [],
    ),
  'setDramaStatus' : IDL.Func([IDL.Text, Status], [IDL.Bool], []),
  'toggleCategoryActive' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'unblockUser' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'updateAppConfig' : IDL.Func([AppConfig], [AppConfig], []),
  'updateCategory' : IDL.Func([IDL.Text, Category], [IDL.Opt(Category)], []),
  'updateCreator' : IDL.Func([IDL.Text, Creator], [IDL.Opt(Creator)], []),
  'updateDrama' : IDL.Func([IDL.Text, Drama], [IDL.Opt(Drama)], []),
  'updateEpisode' : IDL.Func([IDL.Text, Episode], [IDL.Opt(Episode)], []),
  'updateSubscriptionStatus' : IDL.Func(
      [IDL.Text, SubscriptionStatus],
      [IDL.Bool],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Category = IDL.Record({
    'id' : IDL.Text,
    'active' : IDL.Bool,
    'order' : IDL.Nat,
    'icon' : IDL.Text,
    'name' : IDL.Text,
    'color' : IDL.Text,
  });
  const Creator = IDL.Record({
    'id' : IDL.Text,
    'bio' : IDL.Text,
    'verified' : IDL.Bool,
    'name' : IDL.Text,
    'totalVideos' : IDL.Nat,
    'followers' : IDL.Nat,
    'avatar' : IDL.Text,
  });
  const Status = IDL.Variant({
    'active' : IDL.Null,
    'draft' : IDL.Null,
    'archived' : IDL.Null,
  });
  const Drama = IDL.Record({
    'id' : IDL.Text,
    'categoryId' : IDL.Text,
    'status' : Status,
    'title' : IDL.Text,
    'shares' : IDL.Nat,
    'thumbnail' : IDL.Text,
    'views' : IDL.Nat,
    'isPremium' : IDL.Bool,
    'coinsRequired' : IDL.Nat,
    'createdAt' : IDL.Int,
    'tags' : IDL.Vec(IDL.Text),
    'creatorId' : IDL.Text,
    'description' : IDL.Text,
    'likes' : IDL.Nat,
    'updatedAt' : IDL.Int,
    'totalParts' : IDL.Nat,
  });
  const Episode = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'duration' : IDL.Nat,
    'thumbnail' : IDL.Text,
    'partNumber' : IDL.Nat,
    'order' : IDL.Nat,
    'views' : IDL.Nat,
    'isPremium' : IDL.Bool,
    'coinsRequired' : IDL.Nat,
    'createdAt' : IDL.Int,
    'videoUrl' : IDL.Text,
    'dramaId' : IDL.Text,
  });
  const AppConfig = IDL.Record({
    'vipMonthlyPrice' : IDL.Float64,
    'maintenanceMode' : IDL.Bool,
    'vipYearlyPrice' : IDL.Float64,
    'coinRewardPerAd' : IDL.Nat,
    'dailyBonusCoins' : IDL.Nat,
  });
  const TransactionType = IDL.Variant({
    'adReward' : IDL.Null,
    'vipPurchase' : IDL.Null,
    'episodeUnlock' : IDL.Null,
    'dailyBonus' : IDL.Null,
    'purchase' : IDL.Null,
  });
  const CoinTransaction = IDL.Record({
    'id' : IDL.Text,
    'transactionType' : TransactionType,
    'userId' : IDL.Nat,
    'createdAt' : IDL.Int,
    'description' : IDL.Text,
    'amount' : IDL.Int,
  });
  const AnalyticsDay = IDL.Record({
    'activeUsers' : IDL.Nat,
    'revenue' : IDL.Float64,
    'totalViews' : IDL.Nat,
    'date' : IDL.Text,
    'totalUsers' : IDL.Nat,
    'newUsers' : IDL.Nat,
    'coinsDistributed' : IDL.Nat,
  });
  const TargetAudience = IDL.Variant({
    'all' : IDL.Null,
    'vip' : IDL.Null,
    'free' : IDL.Null,
  });
  const Notification = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'body' : IDL.Text,
    'sentAt' : IDL.Int,
    'sentBy' : IDL.Text,
    'targetAudience' : TargetAudience,
    'imageUrl' : IDL.Text,
  });
  const SubscriptionStatus = IDL.Variant({
    'active' : IDL.Null,
    'cancelled' : IDL.Null,
    'expired' : IDL.Null,
  });
  const SubscriptionPlan = IDL.Variant({
    'monthly' : IDL.Null,
    'yearly' : IDL.Null,
  });
  const Subscription = IDL.Record({
    'id' : IDL.Text,
    'status' : SubscriptionStatus,
    'endDate' : IDL.Int,
    'userId' : IDL.Nat,
    'plan' : SubscriptionPlan,
    'price' : IDL.Float64,
    'startDate' : IDL.Int,
  });
  const User = IDL.Record({
    'id' : IDL.Nat,
    'favorites' : IDL.Vec(IDL.Text),
    'displayName' : IDL.Text,
    'isBlocked' : IDL.Bool,
    'createdAt' : IDL.Int,
    'coins' : IDL.Nat,
    'watchHistory' : IDL.Vec(IDL.Text),
    'isVIP' : IDL.Bool,
    'phone' : IDL.Text,
    'following' : IDL.Vec(IDL.Text),
    'vipExpiry' : IDL.Opt(IDL.Int),
    'dailyRewardClaimed' : IDL.Bool,
    'avatar' : IDL.Text,
  });
  
  return IDL.Service({
    'adjustUserCoins' : IDL.Func([IDL.Nat, IDL.Int, IDL.Text], [IDL.Bool], []),
    'blockUser' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'createCategory' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Nat],
        [Category],
        [],
      ),
    'createCreator' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [Creator],
        [],
      ),
    'createDrama' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Vec(IDL.Text),
          IDL.Bool,
          IDL.Nat,
        ],
        [Drama],
        [],
      ),
    'createEpisode' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          IDL.Bool,
          IDL.Nat,
        ],
        [Episode],
        [],
      ),
    'deleteCategory' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'deleteDrama' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'deleteEpisode' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'getAppConfig' : IDL.Func([], [AppConfig], ['query']),
    'getCategories' : IDL.Func([], [IDL.Vec(Category)], []),
    'getCoinTransactions' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(CoinTransaction)],
        ['query'],
      ),
    'getCreators' : IDL.Func([], [IDL.Vec(Creator)], ['query']),
    'getDailyAnalytics' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(AnalyticsDay)],
        ['query'],
      ),
    'getDrama' : IDL.Func([IDL.Text], [IDL.Opt(Drama)], []),
    'getDramas' : IDL.Func([], [IDL.Vec(Drama)], []),
    'getEpisodesByDrama' : IDL.Func([IDL.Text], [IDL.Vec(Episode)], []),
    'getNotifications' : IDL.Func([], [IDL.Vec(Notification)], ['query']),
    'getSubscriptions' : IDL.Func([], [IDL.Vec(Subscription)], ['query']),
    'getSummaryStats' : IDL.Func(
        [],
        [
          IDL.Record({
            'revenue' : IDL.Float64,
            'totalViews' : IDL.Nat,
            'activeToday' : IDL.Nat,
            'totalUsers' : IDL.Nat,
          }),
        ],
        ['query'],
      ),
    'getUser' : IDL.Func([IDL.Nat], [IDL.Opt(User)], ['query']),
    'getUserTransactions' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(CoinTransaction)],
        ['query'],
      ),
    'getUsers' : IDL.Func([], [IDL.Vec(User)], ['query']),
    'preupgrade' : IDL.Func([], [], ['oneway']),
    'reorderEpisode' : IDL.Func([IDL.Text, IDL.Nat], [IDL.Bool], []),
    'sendNotification' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, TargetAudience, IDL.Text],
        [Notification],
        [],
      ),
    'setDramaStatus' : IDL.Func([IDL.Text, Status], [IDL.Bool], []),
    'toggleCategoryActive' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'unblockUser' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'updateAppConfig' : IDL.Func([AppConfig], [AppConfig], []),
    'updateCategory' : IDL.Func([IDL.Text, Category], [IDL.Opt(Category)], []),
    'updateCreator' : IDL.Func([IDL.Text, Creator], [IDL.Opt(Creator)], []),
    'updateDrama' : IDL.Func([IDL.Text, Drama], [IDL.Opt(Drama)], []),
    'updateEpisode' : IDL.Func([IDL.Text, Episode], [IDL.Opt(Episode)], []),
    'updateSubscriptionStatus' : IDL.Func(
        [IDL.Text, SubscriptionStatus],
        [IDL.Bool],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };