/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AnalyticsDay {
  'activeUsers' : bigint,
  'revenue' : number,
  'totalViews' : bigint,
  'date' : string,
  'totalUsers' : bigint,
  'newUsers' : bigint,
  'coinsDistributed' : bigint,
}
export interface AppConfig {
  'vipMonthlyPrice' : number,
  'maintenanceMode' : boolean,
  'vipYearlyPrice' : number,
  'coinRewardPerAd' : bigint,
  'dailyBonusCoins' : bigint,
}
export interface Category {
  'id' : string,
  'active' : boolean,
  'order' : bigint,
  'icon' : string,
  'name' : string,
  'color' : string,
}
export interface CoinTransaction {
  'id' : string,
  'transactionType' : TransactionType,
  'userId' : bigint,
  'createdAt' : bigint,
  'description' : string,
  'amount' : bigint,
}
export interface Creator {
  'id' : string,
  'bio' : string,
  'verified' : boolean,
  'name' : string,
  'totalVideos' : bigint,
  'followers' : bigint,
  'avatar' : string,
}
export interface Drama {
  'id' : string,
  'categoryId' : string,
  'status' : Status,
  'title' : string,
  'shares' : bigint,
  'thumbnail' : string,
  'views' : bigint,
  'isPremium' : boolean,
  'coinsRequired' : bigint,
  'createdAt' : bigint,
  'tags' : Array<string>,
  'creatorId' : string,
  'description' : string,
  'likes' : bigint,
  'updatedAt' : bigint,
  'totalParts' : bigint,
}
export interface Episode {
  'id' : string,
  'title' : string,
  'duration' : bigint,
  'thumbnail' : string,
  'partNumber' : bigint,
  'order' : bigint,
  'views' : bigint,
  'isPremium' : boolean,
  'coinsRequired' : bigint,
  'createdAt' : bigint,
  'videoUrl' : string,
  'dramaId' : string,
}
export interface Notification {
  'id' : string,
  'title' : string,
  'body' : string,
  'sentAt' : bigint,
  'sentBy' : string,
  'targetAudience' : TargetAudience,
  'imageUrl' : string,
}
export type Status = { 'active' : null } |
  { 'draft' : null } |
  { 'archived' : null };
export interface Subscription {
  'id' : string,
  'status' : SubscriptionStatus,
  'endDate' : bigint,
  'userId' : bigint,
  'plan' : SubscriptionPlan,
  'price' : number,
  'startDate' : bigint,
}
export type SubscriptionPlan = { 'monthly' : null } |
  { 'yearly' : null };
export type SubscriptionStatus = { 'active' : null } |
  { 'cancelled' : null } |
  { 'expired' : null };
export type TargetAudience = { 'all' : null } |
  { 'vip' : null } |
  { 'free' : null };
export type TransactionType = { 'adReward' : null } |
  { 'vipPurchase' : null } |
  { 'episodeUnlock' : null } |
  { 'dailyBonus' : null } |
  { 'purchase' : null };
export interface User {
  'id' : bigint,
  'favorites' : Array<string>,
  'displayName' : string,
  'isBlocked' : boolean,
  'createdAt' : bigint,
  'coins' : bigint,
  'watchHistory' : Array<string>,
  'isVIP' : boolean,
  'phone' : string,
  'following' : Array<string>,
  'vipExpiry' : [] | [bigint],
  'dailyRewardClaimed' : boolean,
  'avatar' : string,
}
export interface _SERVICE {
  'adjustUserCoins' : ActorMethod<[bigint, bigint, string], boolean>,
  'blockUser' : ActorMethod<[bigint], boolean>,
  'createCategory' : ActorMethod<
    [string, string, string, string, bigint],
    Category
  >,
  'createCreator' : ActorMethod<[string, string, string, string], Creator>,
  'createDrama' : ActorMethod<
    [
      string,
      string,
      string,
      string,
      string,
      string,
      Array<string>,
      boolean,
      bigint,
    ],
    Drama
  >,
  'createEpisode' : ActorMethod<
    [string, string, bigint, string, string, string, bigint, boolean, bigint],
    Episode
  >,
  'deleteCategory' : ActorMethod<[string], boolean>,
  'deleteDrama' : ActorMethod<[string], boolean>,
  'deleteEpisode' : ActorMethod<[string], boolean>,
  'getAppConfig' : ActorMethod<[], AppConfig>,
  'getCategories' : ActorMethod<[], Array<Category>>,
  'getCoinTransactions' : ActorMethod<[bigint], Array<CoinTransaction>>,
  'getCreators' : ActorMethod<[], Array<Creator>>,
  'getDailyAnalytics' : ActorMethod<[bigint], Array<AnalyticsDay>>,
  'getDrama' : ActorMethod<[string], [] | [Drama]>,
  'getDramas' : ActorMethod<[], Array<Drama>>,
  'getEpisodesByDrama' : ActorMethod<[string], Array<Episode>>,
  'getNotifications' : ActorMethod<[], Array<Notification>>,
  'getSubscriptions' : ActorMethod<[], Array<Subscription>>,
  'getSummaryStats' : ActorMethod<
    [],
    {
      'revenue' : number,
      'totalViews' : bigint,
      'activeToday' : bigint,
      'totalUsers' : bigint,
    }
  >,
  'getUser' : ActorMethod<[bigint], [] | [User]>,
  'getUserTransactions' : ActorMethod<[bigint], Array<CoinTransaction>>,
  'getUsers' : ActorMethod<[], Array<User>>,
  'preupgrade' : ActorMethod<[], undefined>,
  'reorderEpisode' : ActorMethod<[string, bigint], boolean>,
  'sendNotification' : ActorMethod<
    [string, string, string, TargetAudience, string],
    Notification
  >,
  'setDramaStatus' : ActorMethod<[string, Status], boolean>,
  'toggleCategoryActive' : ActorMethod<[string], boolean>,
  'unblockUser' : ActorMethod<[bigint], boolean>,
  'updateAppConfig' : ActorMethod<[AppConfig], AppConfig>,
  'updateCategory' : ActorMethod<[string, Category], [] | [Category]>,
  'updateCreator' : ActorMethod<[string, Creator], [] | [Creator]>,
  'updateDrama' : ActorMethod<[string, Drama], [] | [Drama]>,
  'updateEpisode' : ActorMethod<[string, Episode], [] | [Episode]>,
  'updateSubscriptionStatus' : ActorMethod<
    [string, SubscriptionStatus],
    boolean
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];