/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface AppConfig {
    vipMonthlyPrice: number;
    maintenanceMode: boolean;
    vipYearlyPrice: number;
    coinRewardPerAd: bigint;
    dailyBonusCoins: bigint;
}
export interface User {
    id: bigint;
    favorites: Array<string>;
    displayName: string;
    isBlocked: boolean;
    createdAt: bigint;
    coins: bigint;
    watchHistory: Array<string>;
    isVIP: boolean;
    phone: string;
    following: Array<string>;
    vipExpiry?: bigint;
    dailyRewardClaimed: boolean;
    avatar: string;
}
export interface AnalyticsDay {
    activeUsers: bigint;
    revenue: number;
    totalViews: bigint;
    date: string;
    totalUsers: bigint;
    newUsers: bigint;
    coinsDistributed: bigint;
}
export interface Creator {
    id: string;
    bio: string;
    verified: boolean;
    name: string;
    totalVideos: bigint;
    followers: bigint;
    avatar: string;
}
export interface Subscription {
    id: string;
    status: SubscriptionStatus;
    endDate: bigint;
    userId: bigint;
    plan: SubscriptionPlan;
    price: number;
    startDate: bigint;
}
export interface Episode {
    id: string;
    title: string;
    duration: bigint;
    thumbnail: string;
    partNumber: bigint;
    order: bigint;
    views: bigint;
    isPremium: boolean;
    coinsRequired: bigint;
    createdAt: bigint;
    videoUrl: string;
    dramaId: string;
}
export interface CoinTransaction {
    id: string;
    transactionType: TransactionType;
    userId: bigint;
    createdAt: bigint;
    description: string;
    amount: bigint;
}
export interface Notification {
    id: string;
    title: string;
    body: string;
    sentAt: bigint;
    sentBy: string;
    targetAudience: TargetAudience;
    imageUrl: string;
}
export interface Category {
    id: string;
    active: boolean;
    order: bigint;
    icon: string;
    name: string;
    color: string;
}
export interface Drama {
    id: string;
    categoryId: string;
    status: Status;
    title: string;
    shares: bigint;
    thumbnail: string;
    views: bigint;
    isPremium: boolean;
    coinsRequired: bigint;
    createdAt: bigint;
    tags: Array<string>;
    creatorId: string;
    description: string;
    likes: bigint;
    updatedAt: bigint;
    totalParts: bigint;
}
export enum Status {
    active = "active",
    draft = "draft",
    archived = "archived"
}
export enum SubscriptionPlan {
    monthly = "monthly",
    yearly = "yearly"
}
export enum SubscriptionStatus {
    active = "active",
    cancelled = "cancelled",
    expired = "expired"
}
export enum TargetAudience {
    all = "all",
    vip = "vip",
    free = "free"
}
export enum TransactionType {
    adReward = "adReward",
    vipPurchase = "vipPurchase",
    episodeUnlock = "episodeUnlock",
    dailyBonus = "dailyBonus",
    purchase = "purchase"
}
export interface backendInterface {
    adjustUserCoins(uid: bigint, amount: bigint, _reason: string): Promise<boolean>;
    blockUser(uid: bigint): Promise<boolean>;
    createCategory(id: string, name: string, icon: string, color: string, order: bigint): Promise<Category>;
    createCreator(id: string, name: string, avatar: string, bio: string): Promise<Creator>;
    createDrama(id: string, title: string, desc: string, thumbnail: string, categoryId: string, creatorId: string, tags: Array<string>, isPremium: boolean, coinsRequired: bigint): Promise<Drama>;
    createEpisode(dramaId: string, id: string, partNumber: bigint, title: string, videoUrl: string, thumbnail: string, duration: bigint, isPremium: boolean, coinsRequired: bigint): Promise<Episode>;
    deleteCategory(id: string): Promise<boolean>;
    deleteDrama(id: string): Promise<boolean>;
    deleteEpisode(id: string): Promise<boolean>;
    getAppConfig(): Promise<AppConfig>;
    getCategories(): Promise<Array<Category>>;
    getCoinTransactions(_limit: bigint): Promise<Array<CoinTransaction>>;
    getCreators(): Promise<Array<Creator>>;
    getDailyAnalytics(_days: bigint): Promise<Array<AnalyticsDay>>;
    getDrama(id: string): Promise<Drama | null>;
    getDramas(): Promise<Array<Drama>>;
    getEpisodesByDrama(dramaId: string): Promise<Array<Episode>>;
    getNotifications(): Promise<Array<Notification>>;
    getSubscriptions(): Promise<Array<Subscription>>;
    getSummaryStats(): Promise<{
        revenue: number;
        totalViews: bigint;
        activeToday: bigint;
        totalUsers: bigint;
    }>;
    getUser(uid: bigint): Promise<User | null>;
    getUserTransactions(uid: bigint): Promise<Array<CoinTransaction>>;
    getUsers(): Promise<Array<User>>;
    preupgrade(): Promise<void>;
    reorderEpisode(id: string, newOrder: bigint): Promise<boolean>;
    sendNotification(_title: string, _body: string, _imageUrl: string, _targetAudience: TargetAudience, _sentBy: string): Promise<Notification>;
    setDramaStatus(id: string, status: Status): Promise<boolean>;
    toggleCategoryActive(id: string): Promise<boolean>;
    unblockUser(uid: bigint): Promise<boolean>;
    updateAppConfig(fields: AppConfig): Promise<AppConfig>;
    updateCategory(id: string, fields: Category): Promise<Category | null>;
    updateCreator(id: string, fields: Creator): Promise<Creator | null>;
    updateDrama(id: string, fields: Drama): Promise<Drama | null>;
    updateEpisode(id: string, fields: Episode): Promise<Episode | null>;
    updateSubscriptionStatus(id: string, status: SubscriptionStatus): Promise<boolean>;
}
import type { Category as _Category, CoinTransaction as _CoinTransaction, Creator as _Creator, Drama as _Drama, Episode as _Episode, Notification as _Notification, Status as _Status, Subscription as _Subscription, SubscriptionPlan as _SubscriptionPlan, SubscriptionStatus as _SubscriptionStatus, TargetAudience as _TargetAudience, TransactionType as _TransactionType, User as _User } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async adjustUserCoins(arg0: bigint, arg1: bigint, arg2: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.adjustUserCoins(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adjustUserCoins(arg0, arg1, arg2);
            return result;
        }
    }
    async blockUser(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.blockUser(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.blockUser(arg0);
            return result;
        }
    }
    async createCategory(arg0: string, arg1: string, arg2: string, arg3: string, arg4: bigint): Promise<Category> {
        if (this.processError) {
            try {
                const result = await this.actor.createCategory(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createCategory(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async createCreator(arg0: string, arg1: string, arg2: string, arg3: string): Promise<Creator> {
        if (this.processError) {
            try {
                const result = await this.actor.createCreator(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createCreator(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async createDrama(arg0: string, arg1: string, arg2: string, arg3: string, arg4: string, arg5: string, arg6: Array<string>, arg7: boolean, arg8: bigint): Promise<Drama> {
        if (this.processError) {
            try {
                const result = await this.actor.createDrama(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
                return from_candid_Drama_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createDrama(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
            return from_candid_Drama_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async createEpisode(arg0: string, arg1: string, arg2: bigint, arg3: string, arg4: string, arg5: string, arg6: bigint, arg7: boolean, arg8: bigint): Promise<Episode> {
        if (this.processError) {
            try {
                const result = await this.actor.createEpisode(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createEpisode(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
            return result;
        }
    }
    async deleteCategory(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteCategory(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteCategory(arg0);
            return result;
        }
    }
    async deleteDrama(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteDrama(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteDrama(arg0);
            return result;
        }
    }
    async deleteEpisode(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteEpisode(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteEpisode(arg0);
            return result;
        }
    }
    async getAppConfig(): Promise<AppConfig> {
        if (this.processError) {
            try {
                const result = await this.actor.getAppConfig();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAppConfig();
            return result;
        }
    }
    async getCategories(): Promise<Array<Category>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCategories();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCategories();
            return result;
        }
    }
    async getCoinTransactions(arg0: bigint): Promise<Array<CoinTransaction>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCoinTransactions(arg0);
                return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCoinTransactions(arg0);
            return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCreators(): Promise<Array<Creator>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCreators();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCreators();
            return result;
        }
    }
    async getDailyAnalytics(arg0: bigint): Promise<Array<AnalyticsDay>> {
        if (this.processError) {
            try {
                const result = await this.actor.getDailyAnalytics(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDailyAnalytics(arg0);
            return result;
        }
    }
    async getDrama(arg0: string): Promise<Drama | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getDrama(arg0);
                return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDrama(arg0);
            return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDramas(): Promise<Array<Drama>> {
        if (this.processError) {
            try {
                const result = await this.actor.getDramas();
                return from_candid_vec_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDramas();
            return from_candid_vec_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async getEpisodesByDrama(arg0: string): Promise<Array<Episode>> {
        if (this.processError) {
            try {
                const result = await this.actor.getEpisodesByDrama(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getEpisodesByDrama(arg0);
            return result;
        }
    }
    async getNotifications(): Promise<Array<Notification>> {
        if (this.processError) {
            try {
                const result = await this.actor.getNotifications();
                return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getNotifications();
            return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSubscriptions(): Promise<Array<Subscription>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSubscriptions();
                return from_candid_vec_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSubscriptions();
            return from_candid_vec_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSummaryStats(): Promise<{
        revenue: number;
        totalViews: bigint;
        activeToday: bigint;
        totalUsers: bigint;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getSummaryStats();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSummaryStats();
            return result;
        }
    }
    async getUser(arg0: bigint): Promise<User | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUser(arg0);
                return from_candid_opt_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUser(arg0);
            return from_candid_opt_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserTransactions(arg0: bigint): Promise<Array<CoinTransaction>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserTransactions(arg0);
                return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserTransactions(arg0);
            return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUsers(): Promise<Array<User>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUsers();
                return from_candid_vec_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUsers();
            return from_candid_vec_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async preupgrade(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.preupgrade();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.preupgrade();
            return result;
        }
    }
    async reorderEpisode(arg0: string, arg1: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.reorderEpisode(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.reorderEpisode(arg0, arg1);
            return result;
        }
    }
    async sendNotification(arg0: string, arg1: string, arg2: string, arg3: TargetAudience, arg4: string): Promise<Notification> {
        if (this.processError) {
            try {
                const result = await this.actor.sendNotification(arg0, arg1, arg2, to_candid_TargetAudience_n29(this._uploadFile, this._downloadFile, arg3), arg4);
                return from_candid_Notification_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.sendNotification(arg0, arg1, arg2, to_candid_TargetAudience_n29(this._uploadFile, this._downloadFile, arg3), arg4);
            return from_candid_Notification_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async setDramaStatus(arg0: string, arg1: Status): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.setDramaStatus(arg0, to_candid_Status_n31(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setDramaStatus(arg0, to_candid_Status_n31(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async toggleCategoryActive(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.toggleCategoryActive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.toggleCategoryActive(arg0);
            return result;
        }
    }
    async unblockUser(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.unblockUser(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.unblockUser(arg0);
            return result;
        }
    }
    async updateAppConfig(arg0: AppConfig): Promise<AppConfig> {
        if (this.processError) {
            try {
                const result = await this.actor.updateAppConfig(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateAppConfig(arg0);
            return result;
        }
    }
    async updateCategory(arg0: string, arg1: Category): Promise<Category | null> {
        if (this.processError) {
            try {
                const result = await this.actor.updateCategory(arg0, arg1);
                return from_candid_opt_n33(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateCategory(arg0, arg1);
            return from_candid_opt_n33(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateCreator(arg0: string, arg1: Creator): Promise<Creator | null> {
        if (this.processError) {
            try {
                const result = await this.actor.updateCreator(arg0, arg1);
                return from_candid_opt_n34(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateCreator(arg0, arg1);
            return from_candid_opt_n34(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateDrama(arg0: string, arg1: Drama): Promise<Drama | null> {
        if (this.processError) {
            try {
                const result = await this.actor.updateDrama(arg0, to_candid_Drama_n35(this._uploadFile, this._downloadFile, arg1));
                return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateDrama(arg0, to_candid_Drama_n35(this._uploadFile, this._downloadFile, arg1));
            return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateEpisode(arg0: string, arg1: Episode): Promise<Episode | null> {
        if (this.processError) {
            try {
                const result = await this.actor.updateEpisode(arg0, arg1);
                return from_candid_opt_n37(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateEpisode(arg0, arg1);
            return from_candid_opt_n37(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateSubscriptionStatus(arg0: string, arg1: SubscriptionStatus): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateSubscriptionStatus(arg0, to_candid_SubscriptionStatus_n38(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateSubscriptionStatus(arg0, to_candid_SubscriptionStatus_n38(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
}
function from_candid_CoinTransaction_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CoinTransaction): CoinTransaction {
    return from_candid_record_n7(_uploadFile, _downloadFile, value);
}
function from_candid_Drama_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Drama): Drama {
    return from_candid_record_n2(_uploadFile, _downloadFile, value);
}
function from_candid_Notification_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Notification): Notification {
    return from_candid_record_n14(_uploadFile, _downloadFile, value);
}
function from_candid_Status_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Status): Status {
    return from_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function from_candid_SubscriptionPlan_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SubscriptionPlan): SubscriptionPlan {
    return from_candid_variant_n23(_uploadFile, _downloadFile, value);
}
function from_candid_SubscriptionStatus_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SubscriptionStatus): SubscriptionStatus {
    return from_candid_variant_n21(_uploadFile, _downloadFile, value);
}
function from_candid_Subscription_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Subscription): Subscription {
    return from_candid_record_n19(_uploadFile, _downloadFile, value);
}
function from_candid_TargetAudience_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TargetAudience): TargetAudience {
    return from_candid_variant_n16(_uploadFile, _downloadFile, value);
}
function from_candid_TransactionType_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TransactionType): TransactionType {
    return from_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function from_candid_User_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _User): User {
    return from_candid_record_n26(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Drama]): Drama | null {
    return value.length === 0 ? null : from_candid_Drama_n1(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_User]): User | null {
    return value.length === 0 ? null : from_candid_User_n25(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Category]): Category | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Creator]): Creator | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Episode]): Episode | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    title: string;
    body: string;
    sentAt: bigint;
    sentBy: string;
    targetAudience: _TargetAudience;
    imageUrl: string;
}): {
    id: string;
    title: string;
    body: string;
    sentAt: bigint;
    sentBy: string;
    targetAudience: TargetAudience;
    imageUrl: string;
} {
    return {
        id: value.id,
        title: value.title,
        body: value.body,
        sentAt: value.sentAt,
        sentBy: value.sentBy,
        targetAudience: from_candid_TargetAudience_n15(_uploadFile, _downloadFile, value.targetAudience),
        imageUrl: value.imageUrl
    };
}
function from_candid_record_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: _SubscriptionStatus;
    endDate: bigint;
    userId: bigint;
    plan: _SubscriptionPlan;
    price: number;
    startDate: bigint;
}): {
    id: string;
    status: SubscriptionStatus;
    endDate: bigint;
    userId: bigint;
    plan: SubscriptionPlan;
    price: number;
    startDate: bigint;
} {
    return {
        id: value.id,
        status: from_candid_SubscriptionStatus_n20(_uploadFile, _downloadFile, value.status),
        endDate: value.endDate,
        userId: value.userId,
        plan: from_candid_SubscriptionPlan_n22(_uploadFile, _downloadFile, value.plan),
        price: value.price,
        startDate: value.startDate
    };
}
function from_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    categoryId: string;
    status: _Status;
    title: string;
    shares: bigint;
    thumbnail: string;
    views: bigint;
    isPremium: boolean;
    coinsRequired: bigint;
    createdAt: bigint;
    tags: Array<string>;
    creatorId: string;
    description: string;
    likes: bigint;
    updatedAt: bigint;
    totalParts: bigint;
}): {
    id: string;
    categoryId: string;
    status: Status;
    title: string;
    shares: bigint;
    thumbnail: string;
    views: bigint;
    isPremium: boolean;
    coinsRequired: bigint;
    createdAt: bigint;
    tags: Array<string>;
    creatorId: string;
    description: string;
    likes: bigint;
    updatedAt: bigint;
    totalParts: bigint;
} {
    return {
        id: value.id,
        categoryId: value.categoryId,
        status: from_candid_Status_n3(_uploadFile, _downloadFile, value.status),
        title: value.title,
        shares: value.shares,
        thumbnail: value.thumbnail,
        views: value.views,
        isPremium: value.isPremium,
        coinsRequired: value.coinsRequired,
        createdAt: value.createdAt,
        tags: value.tags,
        creatorId: value.creatorId,
        description: value.description,
        likes: value.likes,
        updatedAt: value.updatedAt,
        totalParts: value.totalParts
    };
}
function from_candid_record_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    favorites: Array<string>;
    displayName: string;
    isBlocked: boolean;
    createdAt: bigint;
    coins: bigint;
    watchHistory: Array<string>;
    isVIP: boolean;
    phone: string;
    following: Array<string>;
    vipExpiry: [] | [bigint];
    dailyRewardClaimed: boolean;
    avatar: string;
}): {
    id: bigint;
    favorites: Array<string>;
    displayName: string;
    isBlocked: boolean;
    createdAt: bigint;
    coins: bigint;
    watchHistory: Array<string>;
    isVIP: boolean;
    phone: string;
    following: Array<string>;
    vipExpiry?: bigint;
    dailyRewardClaimed: boolean;
    avatar: string;
} {
    return {
        id: value.id,
        favorites: value.favorites,
        displayName: value.displayName,
        isBlocked: value.isBlocked,
        createdAt: value.createdAt,
        coins: value.coins,
        watchHistory: value.watchHistory,
        isVIP: value.isVIP,
        phone: value.phone,
        following: value.following,
        vipExpiry: record_opt_to_undefined(from_candid_opt_n27(_uploadFile, _downloadFile, value.vipExpiry)),
        dailyRewardClaimed: value.dailyRewardClaimed,
        avatar: value.avatar
    };
}
function from_candid_record_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    transactionType: _TransactionType;
    userId: bigint;
    createdAt: bigint;
    description: string;
    amount: bigint;
}): {
    id: string;
    transactionType: TransactionType;
    userId: bigint;
    createdAt: bigint;
    description: string;
    amount: bigint;
} {
    return {
        id: value.id,
        transactionType: from_candid_TransactionType_n8(_uploadFile, _downloadFile, value.transactionType),
        userId: value.userId,
        createdAt: value.createdAt,
        description: value.description,
        amount: value.amount
    };
}
function from_candid_variant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    all: null;
} | {
    vip: null;
} | {
    free: null;
}): TargetAudience {
    return "all" in value ? TargetAudience.all : "vip" in value ? TargetAudience.vip : "free" in value ? TargetAudience.free : value;
}
function from_candid_variant_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    active: null;
} | {
    cancelled: null;
} | {
    expired: null;
}): SubscriptionStatus {
    return "active" in value ? SubscriptionStatus.active : "cancelled" in value ? SubscriptionStatus.cancelled : "expired" in value ? SubscriptionStatus.expired : value;
}
function from_candid_variant_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    monthly: null;
} | {
    yearly: null;
}): SubscriptionPlan {
    return "monthly" in value ? SubscriptionPlan.monthly : "yearly" in value ? SubscriptionPlan.yearly : value;
}
function from_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    active: null;
} | {
    draft: null;
} | {
    archived: null;
}): Status {
    return "active" in value ? Status.active : "draft" in value ? Status.draft : "archived" in value ? Status.archived : value;
}
function from_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    adReward: null;
} | {
    vipPurchase: null;
} | {
    episodeUnlock: null;
} | {
    dailyBonus: null;
} | {
    purchase: null;
}): TransactionType {
    return "adReward" in value ? TransactionType.adReward : "vipPurchase" in value ? TransactionType.vipPurchase : "episodeUnlock" in value ? TransactionType.episodeUnlock : "dailyBonus" in value ? TransactionType.dailyBonus : "purchase" in value ? TransactionType.purchase : value;
}
function from_candid_vec_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Drama>): Array<Drama> {
    return value.map((x)=>from_candid_Drama_n1(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Notification>): Array<Notification> {
    return value.map((x)=>from_candid_Notification_n13(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Subscription>): Array<Subscription> {
    return value.map((x)=>from_candid_Subscription_n18(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_User>): Array<User> {
    return value.map((x)=>from_candid_User_n25(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_CoinTransaction>): Array<CoinTransaction> {
    return value.map((x)=>from_candid_CoinTransaction_n6(_uploadFile, _downloadFile, x));
}
function to_candid_Drama_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Drama): _Drama {
    return to_candid_record_n36(_uploadFile, _downloadFile, value);
}
function to_candid_Status_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Status): _Status {
    return to_candid_variant_n32(_uploadFile, _downloadFile, value);
}
function to_candid_SubscriptionStatus_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SubscriptionStatus): _SubscriptionStatus {
    return to_candid_variant_n39(_uploadFile, _downloadFile, value);
}
function to_candid_TargetAudience_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TargetAudience): _TargetAudience {
    return to_candid_variant_n30(_uploadFile, _downloadFile, value);
}
function to_candid_record_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    categoryId: string;
    status: Status;
    title: string;
    shares: bigint;
    thumbnail: string;
    views: bigint;
    isPremium: boolean;
    coinsRequired: bigint;
    createdAt: bigint;
    tags: Array<string>;
    creatorId: string;
    description: string;
    likes: bigint;
    updatedAt: bigint;
    totalParts: bigint;
}): {
    id: string;
    categoryId: string;
    status: _Status;
    title: string;
    shares: bigint;
    thumbnail: string;
    views: bigint;
    isPremium: boolean;
    coinsRequired: bigint;
    createdAt: bigint;
    tags: Array<string>;
    creatorId: string;
    description: string;
    likes: bigint;
    updatedAt: bigint;
    totalParts: bigint;
} {
    return {
        id: value.id,
        categoryId: value.categoryId,
        status: to_candid_Status_n31(_uploadFile, _downloadFile, value.status),
        title: value.title,
        shares: value.shares,
        thumbnail: value.thumbnail,
        views: value.views,
        isPremium: value.isPremium,
        coinsRequired: value.coinsRequired,
        createdAt: value.createdAt,
        tags: value.tags,
        creatorId: value.creatorId,
        description: value.description,
        likes: value.likes,
        updatedAt: value.updatedAt,
        totalParts: value.totalParts
    };
}
function to_candid_variant_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TargetAudience): {
    all: null;
} | {
    vip: null;
} | {
    free: null;
} {
    return value == TargetAudience.all ? {
        all: null
    } : value == TargetAudience.vip ? {
        vip: null
    } : value == TargetAudience.free ? {
        free: null
    } : value;
}
function to_candid_variant_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Status): {
    active: null;
} | {
    draft: null;
} | {
    archived: null;
} {
    return value == Status.active ? {
        active: null
    } : value == Status.draft ? {
        draft: null
    } : value == Status.archived ? {
        archived: null
    } : value;
}
function to_candid_variant_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SubscriptionStatus): {
    active: null;
} | {
    cancelled: null;
} | {
    expired: null;
} {
    return value == SubscriptionStatus.active ? {
        active: null
    } : value == SubscriptionStatus.cancelled ? {
        cancelled: null
    } : value == SubscriptionStatus.expired ? {
        expired: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
